apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-jpa-postgres
  labels:
    app: boot-jpa-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-jpa-postgres
  template:
    metadata:
      labels:
        app: boot-jpa-postgres
    spec:
      containers:
        - name: boot-jpa-postgres
          image: zalkdo/boot-jpa-postgres
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boot-jpa-postgres
  name: boot-jpa-postgres
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: boot-jpa-postgres